# Generated by Django 4.2.1 on 2023-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coschedulecodechallengeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(max_length=100),
        ),
    ]
